CREATE TABLE crm_clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) DEFAULT NULL,
    type_client VARCHAR(50) DEFAULT NULL,
    identite_type VARCHAR(50) DEFAULT NULL,
    identite_numero VARCHAR(100) DEFAULT NULL,
    identite_doc VARCHAR(255) DEFAULT NULL,
    contact_principal VARCHAR(100) DEFAULT NULL,
    contact_secondaire VARCHAR(100) DEFAULT NULL,
    email VARCHAR(100) DEFAULT NULL,
    adresse TEXT DEFAULT NULL,
    ville VARCHAR(100) DEFAULT NULL,
    code_postal VARCHAR(20) DEFAULT NULL,
    pays VARCHAR(100) DEFAULT NULL,
    source VARCHAR(100) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    agency_id INT UNSIGNED DEFAULT NULL,
    agent_id INT UNSIGNED DEFAULT NULL,
    date_creation DATETIME DEFAULT CURRENT_TIMESTAMP,
    date_modification DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_agency_id (agency_id),
    INDEX idx_agent_id (agent_id)
);
